name: Review with labels

on:
  pull_request:
    types: [labeled]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/github-script@0.8.0
        name: Not an Action
        if: github.event.label.name == 'nocode' || github.event.label.name == 'not-an-action'
        with:
          script: |
            await github.issues.createComment({
              owner: "LulaV14",
              repo: "android_demo",
              issue_number: context.payload.number,
              body: "Submission is not a usable GitHub Action"
            });

            await github.pulls.update({
              owner: "LulaV14",
              repo: "android_demo",
              pull_number: context.payload.number,
              state: "closed"
            });
      - uses: actions/github-script@0.8.0
        name: Featured
        if: github.event.label.name == 'featured' || github.event.label.name == 'good'
        with:
          script: |
            await github.pulls.merge({
              owner: "LulaV14",
              repo: "android_demo",
              pull_number: context.payload.number,
            });
      - uses: actions/github-script@0.8.0
        name: Fork
        if: github.event.label.name == 'fork'
        with:
          script: |
            await github.issues.createComment({
              owner: "LulaV14",
              repo: "android_demo",
              issue_number: context.payload.number,
              body: "Submission is a fork and does not represent the submitter as the author."
            });

            await github.pulls.update({
              owner: "LulaV14",
              repo: "android_demo",
              pull_number: context.payload.number,
              state: "closed"
            });
      - uses: actions/github-script@0.8.0
        name: Ended
        if: github.event.label.name == 'late'
        with:
          script: |
            await github.issues.createComment({
              owner: "LulaV14",
              repo: "android_demo",
              issue_number: context.payload.number,
              body: "Submission received after the Hackathon has ended."
            });

            await github.pulls.update({
              owner: "LulaV14",
              repo: "android_demo",
              pull_number: context.payload.number,
              state: "closed"
            });
